name: localp2p_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  ffi: ^2.1.0
  flutter_rust_bridge: ^2.0.0

  # 日志库
  logger: ^2.0.0
  path_provider: ^2.1.0
  path: ^1.8.0
  intl: ^0.18.0
  share_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  ffigen: ^9.0.0

flutter:
  uses-material-design: true
